# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc
# copied from https://github.com/CLIUtils/CLI11

trigger:
  - main

pr:
  - main

variables:
  utilities.std: 17
  utilities.build_type: Debug
  utilities.options: -DGMLC_UTILITIES_BUILD_TESTS=ON -DGMLC_UTILITIES_ENABLE_ERROR_ON_WARNINGS=ON
  CMAKE_BUILD_PARALLEL_LEVEL: 4

jobs:
  - job: ClangTidy
    variables:
      CXX_FLAGS: '-Werror -Wcast-align -Wfloat-equal -Wimplicit-atomic-properties -Wmissing-declarations -Woverlength-strings -Wshadow -Wstrict-selector-match -Wundeclared-selector -Wunreachable-code -std=c++17'
      utilities.options: -DGMLC_UTILITIES_CLANG_TIDY=ON -DGMLC_UTILITIES_CLANG_TIDY_OPTIONS="-fix"
      utilities.std: 17
      CMAKE_BUILD_PARALLEL_LEVEL: 1
    pool:
      vmImage: 'ubuntu-latest'
    container: helics/buildenv:clang14-builder
    steps:
      - template: .ci/azure-build.yml
      - script: git diff --exit-code --color
        displayName: Check tidy

  - job: CppLint
    variables:
      utilities.options:
    pool:
      vmImage: 'ubuntu-latest'
    container: helics/buildenv:cpplint
    steps:
      - bash: cpplint --counting=detailed --recursive gmlc tests benchmarks
        displayName: Checking against google style guide

  - job: Native
    strategy:
      matrix:
        Linux17:
          vmImage: 'ubuntu-latest'
        macOS20:
          vmImage: 'macOS-latest'
          utilities.std: 20
        macOS17:
          vmImage: 'macOS-latest'
        Windows20:
          vmImage: 'windows-2019'
          utilities.std: 20
        Windows17:
          vmImage: 'windows-2019'
        Windowslatest:
          vmImage: 'windows-2022'
          utilities.std: 20
    pool:
      vmImage: $(vmImage)
    steps:
      - template: .ci/azure-build.yml
      - template: .ci/azure-test.yml

  - job: Docker
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        gcc8:
          containerImage: helics/buildenv:gcc8-builder
        gcc9:
          containerImage: helics/buildenv:gcc9-builder
          utilities.options: -DCMAKE_CXX_FLAGS="-Wstrict-overflow=5"
        gcc12:
          containerImage: helics/buildenv:gcc12-builder
          utilities.std: 20
        clang9:
          containerImage: helics/buildenv:clang9-builder
        clang14:
          containerImage: helics/buildenv:clang14-builder
          utilities.std: 20
    container: $[ variables['containerImage'] ]
    steps:
      - template: .ci/azure-build.yml
      - template: .ci/azure-test.yml
